SELECT * FROM CHAT_MEMBERS ORDER BY CHAT_CODE

SELECT * FROM USERS
SELECT * FROM CHAT_ROOM
SELECT * FROM CHAT_LOGS

INSERT INTO CHAT_LOGS(chat_code, USER_CODE, CHAT_LOG, time)
VALUES(6, 6, '하이요(주영)', '08:01')

SELECT USER_CODE FROM CHAT_MEMBERS mem WHERE mem.CHAT_CODE=1

select user_img from users where user_code=8